notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=ckanext setup.py test
#- coverage report -m
- flake8 ckanext
after_success:
- codecov
before_deploy:
#- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "kyIDSNjSYrgexdCU1Crdpxy6LsVxSDNq1LM9YrchSxIJ0MA8DpxALRnfASZ32ZorphAlZDc1gOiUAFkc1/PCAvu66MoZ87v5Pqt5wwd/NlGOfQii5/1kG1a0SWh20FkBpC90Eha3NKsStjPXWbSLDMCzx1Y7m7Wj0l2hFQBuXQeuUikQo0Ecrb4uvN6PMtkhwIgs2+UPOfNxhuvaqi31YITCFaAD3VKT/jvo2tjesGSkQFyBPvJ+HTa4MIl//uHqUX77WBOLwA2ei1vYcUAhoQhiNV4YE3Ics8Xrhv6d7+ASpWgTfIFl5Wvi9YwTMmyKW+BSb+RvUcyK9oXZve86QF/R1unoEO5BbNIi4iqqDuFVZdFuuGWyHXU+ErFh18MA1vGUp1AsAJhtoZ58HSTe21dImem9bf7SALBOGqiyzr582TGlIUSwXfQNLscXcNfLlqFsDusGm51Poqupnf9T5LYDoBglmyL6y7/6Tejrnz5zrUGc9R53etXCXEk/a19ZLfMTQuIJqsYDgMF/fFD7dlYPUOLAOCAJZ3yWzAgXa2aMv3DIVX4JRo2821i7gTIg2FTu4mhfUJBNdN3zXaWSP8kMoH/ZEgSrS+P/ROBwup5eybMRgdGwLILMQszon1WpEjONaBMoFCQ8XmRBGUwQ4LxbVkmHCpADOx50FZdHfKE="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
